### PR TITLE
fix:(graphiql) - for SSR, regression from extraKeys bugfix, fixes #942 

### LINKED ISSUE #942: window is not defined in SSR mode @0.14.0
See title. @0.13.2 all OK

```
(node:22785) ExperimentalWarning: The ESM module loader is experimental.
18|uae-realty-front:3820  | modules/Avatar deprecated. Use ui/Avatar instead
18|uae-realty-front:3820  | ReferenceError: window is not defined
18|uae-realty-front:3820  |     at Object.<anonymous> (/var/www/uae/uae-realty/node_modules/graphiql/dist/utility/commonKeys.js:12:15)
18|uae-realty-front:3820  |     at Module._compile (internal/modules/cjs/loader.js:688:30)
18|uae-realty-front:3820  |     at Module._compile (/var/www/uae/uae-realty/node_modules/pirates/lib/index.js:99:24)
18|uae-realty-front:3820  |     at Module._extensions..js (internal/modules/cjs/loader.js:699:10)
18|uae-realty-front:3820  |     at Object.newLoader [as .js] (/var/www/uae/uae-realty/node_modules/pirates/lib/index.js:104:7)
18|uae-realty-front:3820  |     at Module.load (internal/modules/cjs/loader.js:598:32)
18|uae-realty-front:3820  |     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
18|uae-realty-front:3820  |     at Function.Module._load (internal/modules/cjs/loader.js:529:3)
18|uae-realty-front:3820  |     at Module.require (internal/modules/cjs/loader.js:636:17)
18|uae-realty-front:3820  |     at require (internal/modules/cjs/helpers.js:20:18)

```

### PR DESCRIPTION
**Pull request by acao**
- dont expect window to be present for extraKeys MacOs detection logic
- use existing graphiql convention for detecting the presence of window

### CODE REVIEW

File: packages/graphiql/src/utility/commonKeys.js [hunk 1]
```diff
@@ -1,4 +1,8 @@
-const isMacOs = window.navigator.platform === 'MacIntel';
+let isMacOs = false
+
+if (typeof window === Object) {
```
Comment (benjie) [inline packages/graphiql/src/utility/commonKeys.js]: This isn't correct; you meant

```
if (typeof window !== 'undefined') {
```

(preferred); or alternatively:

```
if (typeof window === 'object') {
```

Comment (benjie) [reply packages/graphiql/src/utility/commonKeys.js]: I'll send a PR

Comment (benjie) [reply packages/graphiql/src/utility/commonKeys.js]: Ah; fixed on master :+1:
