### PR TITLE
fix: headers tab - highlighting and schema fetch

### LINKED ISSUE #1592: bug: headers editor does not add headers to schema fetch
oops!

headers editor does not add headers to the schema fetch.

currently you need to manually add them to your `fetcher` function.

this was something I overlooked in PR review, my bad!

### PR DESCRIPTION
**Pull request by acao**
- headers tab does not re-fetch schema with same headers when fetcher prop changes
- codemirror mode for json, `graphql-headers` is a non-existant mode
- resolves #1592

### CODE REVIEW

File: packages/graphiql/src/components/HeaderEditor.tsx [hunk 1]
```diff
@@ -71,13 +71,14 @@ export class HeaderEditor extends React.Component<HeaderEditorProps> {
...
     require('codemirror/addon/dialog/dialog');
+    require('codemirror/mode/javascript/javascript');
     require('codemirror/keymap/sublime');
 
     const editor = (this.editor = this.CodeMirror(this._node, {
       value: this.props.value || '',
       lineNumbers: true,
       tabSize: 2,
-      mode: 'graphql-headers',
+      mode: { name: 'javascript', json: true },
```
Comment (connorshea) [inline packages/graphiql/src/components/HeaderEditor.tsx:81]: @acao This was done because the variable editor was set to `graphql-variables`, is that an actual mode or should we change that as well?

https://github.com/graphql/graphiql/blob/1124834c0751fbd560c7909b498c605fb5d0f65d/packages/graphiql/src/components/VariableEditor.tsx#L88

Comment (acao) [reply packages/graphiql/src/components/HeaderEditor.tsx:81]: `graphql-variables` is an actual mode in the `codemirror-graphql` package in this repo, as you can see in the `require()` statements
https://github.com/graphql/graphiql/blob/1124834c0751fbd560c7909b498c605fb5d0f65d/packages/graphiql/src/components/VariableEditor.tsx#L82

Comment (acao) [reply packages/graphiql/src/components/HeaderEditor.tsx:81]: codemirror is not the simplest to wrap your head around, so I can totally relate with this choice! haha
