### PR TITLE
fix initial state computation to avoid duplicate tabs

### LINKED ISSUE #2380: Using headers prop creates new tab on every reload
I've created a repro here: https://stackblitz.com/edit/react-ts-9dagjc?file=GraphiQL.tsx

Try hitting the refresh button on the preview on the right. It seems when i remove the `headers` prop the problem disappears.

### PR DESCRIPTION
**Pull request by thomasheyenbrock**
Fixes #2380 

I refactored the code a bit so that the computation of the initial editor values and the initial tabs happen at the same place. To avoid any inconsistencies we now store the tab state directly after deriving it in the initial render.

### CODE REVIEW

File: packages/graphiql-react/src/editor/tabs.ts [hunk 1]
```diff
@@ -108,15 +110,18 @@ export function getDefaultTabState({
...
 
       return parsed;
     } else {
       throw new Error('Storage for tabs is invalid');
     }
   } catch (err) {
-    storage?.set(STORAGE_KEY, '');
-    return { activeTabIndex: 0, tabs: [emptyTab()] };
+    return {
+      activeTabIndex: 0,
```
Comment (acao) [inline packages/graphiql-react/src/editor/tabs.ts:122]: ah, makes sense!

File: packages/graphiql-react/src/editor/tabs.ts [hunk 2]
```diff
@@ -252,14 +257,18 @@ export function useSetEditorValues({
...
-export function emptyTab(): TabState {
+export function createTab({
+  query = null,
+  variables = null,
+  headers = null,
+}: Partial<Pick<TabState, 'query' | 'variables' | 'headers'>> = {}): TabState {
   return {
     id: guid(),
-    hash: hashFromTabContents({ query: null, variables: null, headers: null }),
+    hash: hashFromTabContents({ query, variables, headers }),
```
Comment (acao) [inline packages/graphiql-react/src/editor/tabs.ts:267]: ✅

**Review by acao — APPROVED** [review]
looks good to me!
