### PR TITLE
avoid top-level dynamic codemirror imports

### LINKED ISSUE #2368: ReferenceError: navigator is not defined (remix react)
Hi There,
I am trying to use GraphiQL with [Hansanghyeon/error-remix-graphiql](https://github.com/Hansanghyeon/error-remix-graphiql) but I am getting following error:

There was a similar issue. #118

```
ReferenceError: navigator is not defined
    at /Users/imweb/@lab/blog-tutorial/node_modules/codemirror/lib/codemirror.js:18:19
    at /Users/imweb/@lab/blog-tutorial/node_modules/codemirror/lib/codemirror.js:11:83
    at Object.<anonymous> (/Users/imweb/@lab/blog-tutorial/node_modules/codemirror/lib/codemirror.js:14:2)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/imweb/@lab/blog-tutorial/node_modules/codemirror/addon/hint/show-hint.js:8:9
    at Object.<anonymous> (/Users/imweb/@lab/blog-tutorial/node_modules/codemirror/addon/hint/show-hint.js:13:3)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
```

### PR DESCRIPTION
**Pull request by thomasheyenbrock**
Fixes #2368 

This should fix breaking imports of `@graphiql/react` (or its dependent `graphiql`) in non-browser environments like Node.js. Remix for example breaks during SSR because these imports also get loaded and executed. `codemirror` assumes to always run in a browser env though.

### CODE REVIEW

**Comment by acao** [comment]
Why are they resolving unresolved promises though? The import should only happen on `await import()` right?

File: packages/graphiql-react/src/editor/common.ts [hunk 1]
```diff
@@ -47,7 +33,20 @@ export async function importCodeMirror(
...
+          import('codemirror/addon/fold/foldgutter'),
+          import('codemirror/addon/lint/lint'),
+          import('codemirror/addon/search/searchcursor'),
+          import('codemirror/addon/search/jump-to-line'),
+          import('codemirror/addon/dialog/dialog'),
+          // @ts-expect-error
+          import('codemirror/keymap/sublime'),
+          ...addons,
+        ];
   await Promise.all(allAddons.map(addon => addon));
```
Comment (B2o5T) [inline packages/graphiql-react/src/editor/common.ts:50]: Not related to your PR, but why we need it? I guess it should be
```suggestion
  await Promise.all(allAddons);
```

**Review by acao — APPROVED** [review]
Hopefully this resolves the issue!

File: packages/graphiql-react/src/editor/common.ts (hunk 1 above)
Comment (acao) [reply packages/graphiql-react/src/editor/common.ts:50]: Yeah this was my original implementation! I wonder what happened?

Comment (B2o5T) [reply packages/graphiql-react/src/editor/common.ts:50]: In this place it makes no sens to do it 🙃

**Comment by thomasheyenbrock** [comment]
This has in fact nothing to do with bundlers after thinking about it again.

In the moment you call `import()` Node.js will dispatch the promise and push it on the call stack. On the next available tick `import` will load the module, thus executing its content.

As an example, you could do the following in Node.js:
- Have a file `dynamic.mjs` like this
  ```js
  console.log("i'm running");
  ```
- Have a file `index.mjs` like this:
  ```js
  function wait(ms) {
    return new Promise((r) => setTimeout(r, ms));
  }

  import("./dynamic.mjs");

  wait(2000).then(() => console.log("done"));
  ```

What you'll see printed is first `i'm running` and then `done`, no matter if you await the dynamic import or not.

File: packages/graphiql-react/src/editor/common.ts (hunk 1 above)
Comment (thomasheyenbrock) [reply packages/graphiql-react/src/editor/common.ts:50]: Oops, now I forgot to include this 🙈

**Comment by acao** [comment]
Indeed! I had a similar realization in the original issue comments. Thus why `React.lazy(() => import())` works for top level declarations, because of the function closure!

File: packages/graphiql-react/src/editor/common.ts (hunk 1 above)
Comment (thomasheyenbrock) [reply packages/graphiql-react/src/editor/common.ts:50]: See #2559
