### PR TITLE
fix(ws): Subscriptions async iterator completes and better error handling

### LINKED ISSUE #1827: How to unsubscribe from graphql-ws subscription
Hello,

When I do a subscription (using graphql-ws fetcher), it works, the results are well printed in the result panel but when I push the stop button, the results stop to be printed on the panel but it seems that nothing is done on the wsClient. GraphiQL does not tell to the wsClient to unsubscribe and events are still sent by the ws server.
If I repush the play button, a second subscription using a different UUID is sent to the server on the same websocket connection which if I'm not mistaken is illegal.
Is there a way to unsubscribe when the stop button is pressed ?
Thx

```javascript
const URL = "http://debian9acu:8000/graphql";
const URLws = "ws://debian9acu:8000/graphql-ws";
var fetcher = createGraphiQLFetcher( {url:URL,subscriptionUrl:URLws} );
const container = document.getElementById("graphiql");
const defaultQuery = `
{
}
`
render(
  <GraphiQL fetcher={fetcher} defaultQuery={defaultQuery} />,
  container
);
```

### PR DESCRIPTION
**Pull request by enisdenjo**
Closes #1827

### CODE REVIEW

File: packages/graphiql-toolkit/src/create-fetcher/lib.ts [hunk 1]
```diff
@@ -92,10 +92,58 @@ export const createWebsocketsFetcherFromUrl = (
...
+      }
+      deferred?.reject(throwMe);
+    },
+    complete: () => {
+      done = true;
+      deferred?.resolve(true);
+    },
+  });
+  return {
+    [Symbol.asyncIterator]() {
```
Comment (n1ru4l) [inline packages/graphiql-toolkit/src/create-fetcher/lib.ts:128]: Note that Symbol.asyncIterator is not available in Safari 14

Comment (enisdenjo) [reply packages/graphiql-toolkit/src/create-fetcher/lib.ts:128]: Also, shouldn't the transpilation be handled by the user? If you'd like to support Safari 14 on iOS, simply polyfill the async iterator with Babel on build step. @acao what is your take on this?

Comment (n1ru4l) [reply packages/graphiql-toolkit/src/create-fetcher/lib.ts:128]: I have no strong feelings about this. For myself, I can say that I am shipping an app with Safari 14 support and try to avoid babel transforms where possible, that is why I created the lib. If GraphiQL does not need to rely on push-pull-async-iterable-iterator I am totally fine with it.

**Comment by enisdenjo** [comment]
Fixed with [`@n1ru4l/push-pull-async-iterable-iterator@v2.1.3`](https://github.com/n1ru4l/push-pull-async-iterable-iterator/releases/tag/v2.1.3).

File: packages/graphiql-toolkit/src/create-fetcher/lib.ts (hunk 1 above)
Comment (enisdenjo) [reply packages/graphiql-toolkit/src/create-fetcher/lib.ts]: Reverted back to using the push-pull-async-iterable-iterator following v2.1.3.

**Comment by enisdenjo** [comment]
Note @n1ru4l, the iterator from `makeAsyncIterableIteratorFromSink` does not throw when calling `sink.error`.

**Comment by n1ru4l** [comment]
https://github.com/n1ru4l/push-pull-async-iterable-iterator/releases/tag/v2.1.4 😰

**Comment by enisdenjo** [comment]
Brilliant! Can confirm `v2.1.4` working @n1ru4l.

@acao this is ready to merge now.

**Comment by n1ru4l** [comment]
Before merging please also reflect whether push-pull-async-iterable-iterator is a necessary dependency @acao 😇

**Comment by acao** [comment]
Appreciate y’all putting so much into this already! Please ping me directly in the future if you have a PR ready for me as I have notifications disabled, and only tend to check on the weekends now that I’m still trying to take a break from maintaining

I don’t have time to look into whether or not that is a necessary dependency @n1ru4l , is it? Should we just merge and release this patch bugfix, and then drop it in a minor release as a follow up at least?

lastly can you... you actually created the changeset... 🥺😍 omg you guys are the best!
